### ISSUE TITLE
Running DAG process cannot be stopped & Sudo privilege issues

### ISSUE THREAD

**Issue by akindemirsec** [ErdemOzgen/blackdagger#18]
When I need to run DAGs that require sudo privileges, the DAG starts but the process stucks. On my local system, I can solve the problem when I authorise my user with "<myusername> ALL= NOPASSWD: ALL" in /etc/sudoers 

The DAG requires sudo priveleges
![1](https://github.com/ErdemOzgen/blackdagger/assets/128565483/f1cde271-811c-44f7-ac19-5b487c7535c8) 

I started the DAG and it got stuck on the first step
![Screenshot from 2024-03-22 15-31-36](https://github.com/ErdemOzgen/blackdagger/assets/128565483/11bdb568-cde9-44fd-ac43-9045aa83a7ff)

Pressed the Stop button
![Screenshot from 2024-03-22 15-31-40](https://github.com/ErdemOzgen/blackdagger/assets/128565483/5b3a5c1f-39b6-42de-ab4a-862183b0787b)

DAG still running and can't stop 
![Screenshot from 2024-03-22 15-31-59](https://github.com/ErdemOzgen/blackdagger/assets/128565483/99c01088-6335-445f-b9cc-288d7b6e2a48)

I've added "myusername> ALL= NOPASSWD: ALL" line in /etc/sudoers
![Screenshot from 2024-03-22 15-53-02](https://github.com/ErdemOzgen/blackdagger/assets/128565483/cbeedbb0-d539-4e37-a603-5daface09ab1)

Now the DAG doesn't stuck and works properly
![Screenshot from 2024-03-22 15-36-08](https://github.com/ErdemOzgen/blackdagger/assets/128565483/86a3e5d6-9982-4888-9f6e-58b32d22f765)

And I can stop the DAG without problem

![Screenshot from 2024-03-22 15-53-02(1)](https://github.com/ErdemOzgen/blackdagger/assets/128565483/faf7aa11-0cdf-4471-b24d-cace61179f21)

**Comment by ErdemOzgen** [comment]
### **If you need root privallages you can use it. 3 different choose you can use.**


1. To ensure continuous operation of the process on your system, simply create and execute the following script every minute via cron—no root account required:

```bash
#!/bin/bash
process="blackdagger start-all"
command="/usr/bin/blackdagger start-all"

if ps ax | grep -v grep | grep "$process" > /dev/null
then
    exit
else
    $command &
fi

exit
```

2. If running as daemon something that you can choose and you need still root privallages you can run:
```bash
sudo blackdagger start-all
```
But this will create **.blackdagger** folder in root user. It may cause python package issues and pip related problems.

3. Last options is adding user account to the /etc/sudoers file with nopasswd permissions, enabling them to execute sudo commands without needing to enter a password. This modification simplifies operations that require elevated privileges by removing the requirement to provide a password for each sudo command.

```bash
# In /etc/sudoers
username ALL=(ALL) NOPASSWD: ALL
```

@GrimezSec Thanks a lot. Good point and good catch !
